
const seasonalItems = {
    Fall: {
        AL: {
            Apples: 'seasonal details',
            Beans: 'seasonal details',
            Blackberries: 'seasonal details',
            Cabbage: 'seasonal details',
            Cantaloupes: 'seasonal details',
            Citrus: 'seasonal details',
            Corn: 'seasonal details',
            Cucumbers: 'seasonal details',
            Eggplant: 'seasonal details',
            Figs: 'seasonal details',
            Grapes: 'seasonal details',
            Greens: 'seasonal details',
            Herbs: 'seasonal details',
            Lettuce: 'seasonal details',
            Okra: 'seasonal details',
            Peaches: 'seasonal details',
            Peas: 'seasonal details',
            Pecans: 'seasonal details',
            Persimmons: 'seasonal details',
            Peppers: 'seasonal details',
            SweetPotatoes: 'seasonal details',
            Pumpkins: 'seasonal details',
            Rutabaga: 'seasonal details',
            Squash: 'seasonal details',
            Tomatoes: 'seasonal details',
            Watermelons: 'seasonal details'},
        AK: {
            Beans: 'seasonal details',
            Beets: 'seasonal details',
            Broccoli: 'seasonal details',
            BrusselSprouts: 'seasonal details',
            Cabbage: 'seasonal details',
            Carrots: 'seasonal details',
            Cauliflower: 'seasonal details',
            Celery: 'seasonal details',
            Chard: 'seasonal details',
            CollardGreens: 'seasonal details',
            Cucumbers: 'seasonal details',
            Kale: 'seasonal details',
            Leeks: 'seasonal details',
            Lettuce: 'seasonal details',
            Onions: 'seasonal details',
            Potatoes: 'seasonal details',
            Pumpkins: 'seasonal details',
            Radishes: 'seasonal details',
            Rhubarb: 'seasonal details',
            Spinach: 'seasonal details',
            Strawberries: 'seasonal details',
            Tomatoes: 'seasonal details',
            Turnips: 'seasonal details',
            Squash: 'seasonal details'},
        AZ: {
            Apples: 'seasonal details',
            Beets: 'seasonal details',
            Broccoli: 'seasonal details',
            Cucumbers: 'seasonal details',
            Dates: 'seasonal details',
            Eggplants: 'seasonal details',
            Grapefruit: 'seasonal details',
            Lemons: 'seasonal details',
            Oranges: 'seasonal details',
            Peaches: 'seasonal details',
            Pears: 'seasonal details',
            Peas: 'seasonal details',
            Pomegranates: 'seasonal details',
            Potatoes: 'seasonal details',
            Pumpkins: 'seasonal details',
            Rasberries: 'seasonal details',
            Spinach: 'seasonal details',
            Squash: 'seasonal details',
            SweetCorn: 'seasonal details',
            Tomatoes: 'seasonal details'},
        AR: {
            Apples: 'seasonal details',
            AsianPears: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details',
            Cucumbers: 'seasonal details',
            Eggplant: 'seasonal details',
            Greens: 'seasonal details',
            Herbs: 'seasonal details',
            Muscadines: 'seasonal details',
            Peaches: 'seasonal details',
            Peppers: 'seasonal details',
            Rasberries: 'seasonal details',
            Pumpkins: 'seasonal details',
            Squash: 'seasonal details',
            SweetCorn: 'seasonal details',
            SweetPotatoes: 'seasonal details',
            Tomatoes: 'seasonal details',
            Watermelons: 'seasonal details'},
        CA: {
            Arugula: 'seasonal details',
            Beans: 'seasonal details',
            Beets: 'seasonal details',
            BlackEyedPeas: 'seasonal details',
            BokChoy: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details',
            Carrots: 'seasonal details',
            Cauliflower: 'seasonal details',
            Celery: 'seasonal details',
            Chard: 'seasonal details',
            Cilantro: 'seasonal details',
            Cucumbers: 'seasonal details',
            Eggplant: 'seasonal details',
            EnglishPeas: 'seasonal details',
            Fennel: 'seasonal details',
            Kale: 'seasonal details',
            Kohlrabi: 'seasonal details',
            Leeks: 'seasonal details',
            Lemons: 'seasonal details',
            Lettuce: 'seasonal details',
            Okra: 'seasonal details',
            Peppers: 'seasonal details',
            Pumpkins: 'seasonal details',
            Radishes: 'seasonal details',
            Rasberries: 'seasonal details',
            SnapPeas: 'seasonal details',
            Spinach: 'seasonal details',
            StringBeans: 'seasonal details',
            Squash: 'seasonal details',
            Tomatoes: 'seasonal details',
            Turnips: 'seasonal details'},
        CO: {
            Apples: 'seasonal details',
            Arugula: 'seasonal details',
            Beets: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details'},
        CT: {
            Apples: 'seasonal details',
            Beans: 'seasonal details',
            Beets: 'seasonal details',
            Blueberries: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details'},
        DE: {
            Apples: 'seasonal details',
            BlackEyedPeas: 'seasonal details',
            BrusselSprouts: 'seasonal details',
            Cabbage: 'seasonal details',
            Carrots: 'seasonal details',
            Cauliflower: 'seasonal details'},
        FL: {
            Avocado: 'seasonal details',
            Cucumber: 'seasonal details',
            Grapefruit: 'seasonal details',
            Mushrooms: 'seasonal details',
            Oranges: 'seasonal details',
            Peanuts: 'seasonal details'},
    },
    Winter: {
        AL: {
            Citrus: 'seasonal details',
            Greens: 'seasonal details',
            Herbs: 'seasonal details',
            Pecans: 'seasonal details',
            Persimmons: 'seasonal details',
            SweetPotatoes: 'seasonal details',
            Rutabaga: 'seasonal details',
            Squash: 'seasonal details'},
        AK: {
            Beets: 'seasonal details',
            Cabbage: 'seasonal details',
            Carrots: 'seasonal details',
            Onions: 'seasonal details',
            Potatoes: 'seasonal details',
            Turnips: 'seasonal details'},
        AZ: {
            Beets: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details',
            Cauliflower: 'seasonal details',
            Carrots: 'seasonal details',
            Celery: 'seasonal details',
            Grapefruit: 'seasonal details',
            Lemons: 'seasonal details',
            Oranges: 'seasonal details',
            Spinach: 'seasonal details',
            Strawberries: 'seasonal details',
            Tangerines: 'seasonal details'},
        AR: {
            spinach: 'seasonal details',
            squash: 'seasonal details',
            turnip: 'seasonal details'},
        CA: {
            Arugula: 'seasonal details',
            Beets: 'seasonal details',
            BokChoy: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details',
            Carrots: 'seasonal details',
            Cauliflower: 'seasonal details',
            Celery: 'seasonal details',
            Cilantro: 'seasonal details',
            Cucumbers: 'seasonal details',
            Eggplant: 'seasonal details',
            EnglishPeas: 'seasonal details',
            Fennel: 'seasonal details',
            Grapefruit: 'seasonal details',
            Kale: 'seasonal details',
            Kohlrabi: 'seasonal details',
            Leeks: 'seasonal details',
            Lemons: 'seasonal details',
            Lettuce: 'seasonal details',
            Mandarins: 'seasonal details',
            NavelOrange: 'seasonal details',
            Parsley: 'seasonal details',
            Peppers: 'seasonal details',
            Radishes: 'seasonal details',
            SnapPeas: 'seasonal details',
            Spinach: 'seasonal details',
            Strawberries: 'seasonal details',
            Turnips: 'seasonal details'},

        CO: {
            Cucumbers: 'seasonal details',
            Potatoes: 'seasonal details',
            Tomatoes: 'seasonal details',
            Squash: 'seasonal details'},
        CT: {
            Beets: 'seasonal details',
            Cauliflower: 'seasonal details',
            Potatoes: 'seasonal details',
            Turnips: 'seasonal details'},
        DE: {
            Turnips: 'seasonal details'},
        FL: {
            BellPeppers: 'seasonal details',
            Cauliflower: 'seasonal details',
            Celery: 'seasonal details',
            Eggplant: 'seasonal details',
            Grapefruit: 'seasonal details',
        },

    },
    Spring: {
        AL: {
            Beans: 'seasonal details',
            Beets: 'seasonal details',
            Blueberries: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details',
            Cauliflower: 'seasonal details',
            Corn: 'seasonal details',
            Cucumbers: 'seasonal details',
            Eggplant: 'seasonal details',
            Greens: 'seasonal details',
            Herbs: 'seasonal details',
            Lettuce: 'seasonal details',
            Onions: 'seasonal details',
            Peaches: 'seasonal details',
            Peas: 'seasonal details',
            Pecans: 'seasonal details',
            SweetPotatoes: 'seasonal details',
            Spinach: 'seasonal details',
            Squash: 'seasonal details',
            Strawberries: 'seasonal details'},
        AK: {
            Beets: 'seasonal details',
            Carrots: 'seasonal details',
            Potatoes: 'seasonal details',
            Rhubsrb: 'seasonal details',
            Tomatoes: 'seasonal details'},
        AZ: {
            Apricots: 'seasonal details',
            Asparagus: 'seasonal details',
            Beets: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details',
            Cauliflower: 'seasonal details',
            Carrots: 'seasonal details',
            Celery: 'seasonal details',
            Cucumbers: 'seasonal details',
            Dates: 'seasonal details',
            Eggplants: 'seasonal details',
            Grapefruit: 'seasonal details',
            Lemons: 'seasonal details',
            Onions: 'seasonal details',
            Oranges: 'seasonal details',
            Spinach: 'seasonal details',
            Squash: 'seasonal details',
            Strawberries: 'seasonal details',
            Tangerines: 'seasonal details',
            Tomatoes: 'seasonal details'},
        AR: {
            Asparagus: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details',
            Cabbage: 'seasonal details',
            Cucumbers: 'seasonal details',
            Greens: 'seasonal details',
            Herbs: 'seasonal details',
            Peas: 'seasonal details',
            Potatoes: 'seasonal details',
            Rhubarb: 'seasonal details',
            Strawberries: 'seasonal details'},
        CA: {
            Beets: 'seasonal details',
            BokChoy: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details',
            Carrots: 'seasonal details',
            Cauliflower: 'seasonal details'},
        CO: {
            Cucumbers: 'seasonal details',
            Lettuce: 'seasonal details',
            Potatoes: 'seasonal details',
            Spinach: 'seasonal details',
            Tomatoes: 'seasonal details'},
        CT: {
            Asparagus: 'seasonal details',
            Beets: 'seasonal details',
            Collards: 'seasonal details',
            Peas: 'seasonal details',
            Rhubarb: 'seasonal details',
            Spinach: 'seasonal details'},
        DE: {
            Asparagus: 'seasonal details',
            GreenOnions: 'seasonal details',
            Lettuce: 'seasonal details',
            Mushrooms: 'seasonal details',
            Peas: 'seasonal details',
            Spinach: 'seasonal details',
            Turnips: 'seasonal details'},
        FL: {
            BellPeppers: 'seasonal details',
            Cabbage: 'seasonal details',
            Celery: 'seasonal details',
            Cucumber: 'seasonal details',
            Eggplant: 'seasonal details',
            Grapefruit: 'seasonal details'},


    },
    Summer: {
        AL: {
            Apples: 'seasonal details',
            Beans: 'seasonal details',
            Beets: 'seasonal details',
            Blackberries: 'seasonal details',
            Blueberries: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details',
            Cantaloupes: 'seasonal details',
            Cauliflower: 'seasonal details',
            Corn: 'seasonal details',
            Cucumbers: 'seasonal details',
            Eggplant: 'seasonal details',
            Figs: 'seasonal details',
            Grapes: 'seasonal details',
            Greens: 'seasonal details',
            Herbs: 'seasonal details',
            Lettuce: 'seasonal details',
            Okra: 'seasonal details',
            Onions: 'seasonal details',
            Peaches: 'seasonal details',
            Peas: 'seasonal details',
            Pecans: 'seasonal details',
            Peppers: 'seasonal details',
            SweetPotatoes: 'seasonal details',
            Spinach: 'seasonal details',
            Squash: 'seasonal details',
            Strawberries: 'seasonal details',
            Tomatoes: 'seasonal details',
            Watermelons: 'seasonal details'},
        AK: {
            Beans: 'seasonal details',
            Beets: 'seasonal details',
            Broccoli: 'seasonal details',
            BrusselSprouts: 'seasonal details',
            Cabbage: 'seasonal details',
            Carrots: 'seasonal details',
            Cauliflower: 'seasonal details',
            Celery: 'seasonal details',
            Chard: 'seasonal details',
            CollardGreens: 'seasonal details',
            Cucumbers: 'seasonal details',
            Kale: 'seasonal details',
            Lettuce: 'seasonal details',
            Onions: 'seasonal details',
            Peas: 'seasonal details',
            Potatoes: 'seasonal details',
            Radishes: 'seasonal details',
            Rasberries: 'seasonal details',
            Rhubarb: 'seasonal details',
            Spinach: 'seasonal details',
            Strawberries: 'seasonal details',
            Tomatoes: 'seasonal details',
            Turnips: 'seasonal details',
            Squash: 'seasonal details',
            Zucchini: 'seasonal details'},
        AZ: {
            Apples: 'seasonal details',
            Apricots: 'seasonal details',
            Beets: 'seasonal details',
            Blackberries: 'seasonal details',
            Blueberries: 'seasonal details',
            Cucumbers: 'seasonal details',
            Dates: 'seasonal details',
            Eggplants: 'seasonal details',
            Figs: 'seasonal details',
            Grapes: 'seasonal details',
            Melons: 'seasonal details',
            Nectarines: 'seasonal details',
            Onions: 'seasonal details',
            Peaches: 'seasonal details',
            Peppers: 'seasonal details',
            Plums: 'seasonal details',
            Pomegranates: 'seasonal details',
            Rasberries: 'seasonal details',
            Squash: 'seasonal details',
            SweetCorn: 'seasonal details',
            Tomatoes: 'seasonal details'},
        AR: {
            Apples: 'seasonal details',
            AsianPears: 'seasonal details',
            Asparagus: 'seasonal details',
            Beans: 'seasonal details',
            Blackberries: 'seasonal details',
            Blueberries: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details',
            Cantaloupes: 'seasonal details',
            Cherries: 'seasonal details',
            Cucumbers: 'seasonal details',
            Eggplant: 'seasonal details',
            Grapes: 'seasonal details',
            Greens: 'seasonal details',
            Herbs: 'seasonal details',
            Nectarines: 'seasonal details',
            Peaches: 'seasonal details',
            Peppers: 'seasonal details',
            Plums: 'seasonal details',
            Potatoes: 'seasonal details',
            Rasberries: 'seasonal details',
            Rhubarb: 'seasonal details',
            Squash: 'seasonal details',
            Strawberries: 'seasonal details',
            SweetCorn: 'seasonal details',
            Tomatoes: 'seasonal details',
            Watermelons: 'seasonal details'},
        CA: {
            Apricots: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/apricots.jpg?h=c8b8df1c&itok=PiYJ9sg1', 'seasonal details'],
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'seasonal details'],
            // Blackberries: [url, 'seasonal details'],
            // BlackEyedPeas: [url, 'seasonal details'],
            BokChoy: ['https://en.wikipedia.org/wiki/File:Bok_Choy_(49553125456).jpg', 'seasonal details']},
        CO: {
            Apricots: 'seasonal details',
            Arugula: 'seasonal details',
            Beets: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details',
            Cauliflower: 'seasonal details'},
        CT: {
            Apples: 'seasonal details',
            Beans: 'seasonal details',
            Beets: 'seasonal details',
            Blackberries: 'seasonal details',
            Blueberries: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details'},
        DE: {
            Apples: 'seasonal details',
            Blueberries: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details',
            Canteloupe: 'seasonal details',
            Carrots: 'seasonal details',
            Cauliflower: 'seasonal details'},
        FL: {
            Avocado: 'seasonal details',
            Guava: 'seasonal details',
            Mango: 'seasonal details',
            Mushrooms: 'seasonal details',
            Peanuts: 'seasonal details',
            Watermelons: 'seasonal details'},

    }
};

export default seasonalItems;
