
const seasonalItems = {
    Fall: {
        AL: {
            Apples: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/apples_2.jpg?h=65b39431&itok=MoJheg5x', 'Apples'],
            Beans: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/green%20beans.jpg?itok=rXeZ3ZNC', 'Beans'],
            Blackberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/blackberries.jpg?h=c8b8df1c&itok=sViCstBs', 'Blackberries'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Cantaloupes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cantaloupe.jpg?h=c8b8df1c&itok=hLzdNse1', 'Cantelopes'],
            Citrus: ['url', 'seasonal details'],
            Corn: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/corn.jpg?itok=I9hbBWX0', 'Corn'],
            Cucumbers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cucumbers2.jpg?itok=YISLeW4e', 'Cucumbers'],
            Eggplant: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasofnal-produce/2018-05/eggplant.jpg?itok=FyEpBSrd', 'Eggplant'],
            Figs: ['https://plantsbymail.com/wp-content/uploads/2018/06/Fig_Little_Miss_Figgy_MAIN.jpg', 'Figs'],
            Grapes: ['url', 'seasonal details'],
            Greens: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/collards.jpg?itok=io-TE89d', 'Greens'],
            Herbs: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/2021-04/herbs.jpg?itok=g_UukhUg', 'Herbs'],
            Lettuce: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/lettuce.jpg?itok=MvYHJXC5', 'Lettuce'],
            Okra: ['url', 'seasonal details'],
            Peaches: ['url', 'seasonal details'],
            Peas: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/peas.jpg?itok=T6KM1bft', 'Peas'],
            Pecans: ['url', 'seasonal details'],
            Persimmons: ['https://nutritioncenter.ctahr.hawaii.edu/wp-content/uploads/2022/06/persimmons-japanese-raw.jpg', 'Persimmons'],
            Peppers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/bell%20peppers.jpg?h=9f30bee3&itok=PKmzyeNv', 'Peppers'],
            SweetPotatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/potatoes.jpg?itok=e3KKT2ta', 'Sweet Potatoes'],
            Pumpkins: ['url', 'seasonal details'],
            Rutabaga: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/rutabaga.jpg?itok=ohK71nUz', 'Rutabaga'],
            Squash: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/summer%20squash.jpg?itok=QPc9_LQw', 'Squash'],
            Tomatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/tomatoes.jpg?itok=JhlM9Onh', 'Tomatoes'],
            Watermelons: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/watermelon.jpg?itok=6EdNOdUo', 'Watermelons']},
        AK: {
            Beans: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/green%20beans.jpg?itok=rXeZ3ZNC', 'Beans'],
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            BrusselSprouts: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/brusselssprouts.jpg?h=c8b8df1c&itok=WsaCU63W', 'Brussel Sprouts'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Carrots: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/carrots.jpg?h=c8b8df1c&itok=wy-UEFSx', 'Carrots'],
            Cauliflower: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cauliflower.jpg?h=c8b8df1c&itok=XVi8_6bg', 'Cauliflower'],
            Celery: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/celery.jpg?h=8bf7d235&itok=5W-SSPx2', 'Celery'],
            Chard: ['url', 'seasonal details'],
            CollardGreens: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/collards.jpg?itok=io-TE89d', 'Greens'],
            Cucumbers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cucumbers2.jpg?itok=YISLeW4e', 'Cucumbers'],
            Kale: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/kale.jpg?itok=Zn8Cux6F', 'Kale'],
            Leeks: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/leeks.jpg?itok=Y8Xlwrgp', 'Leeks'],
            Lettuce: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/lettuce.jpg?itok=MvYHJXC5', 'Lettuce'],
            Onions: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/onions.jpg?itok=oLl36ia1', 'Onions'],
            Potatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/potatoes.jpg?itok=e3KKT2ta', 'Potatoes'],
            Pumpkins: ['url', 'seasonal details'],
            Radishes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/radish.jpg?itok=hNtVXvda', 'Radishes'],
            Rhubarb: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/rhubarb.jpg?itok=N3ThN-Kr', 'Rhubarb'],
            Spinach: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/spinach.jpg?itok=vs_2VYRs', 'Spinach'],
            Strawberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/strawberries.jpg?itok=WXVLbw1Q', 'Strawberries'],
            Tomatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/tomatoes.jpg?itok=JhlM9Onh', 'Tomatoes'],
            Turnips: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/turnips.jpg?itok=ZoofKY5b', 'Turnips'],
            Squash: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/summer%20squash.jpg?itok=QPc9_LQw', 'Squash']},
        AZ: {
            Apples: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/apples_2.jpg?h=65b39431&itok=MoJheg5x', 'Apples'],
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            Cucumbers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cucumbers2.jpg?itok=YISLeW4e', 'Cucumbers'],
            Dates: ['url', 'seasonal details'],
            Eggplants: ['url', 'seasonal details'],
            Grapefruit: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/grapefruit.jpg?itok=EXi1a_uq', 'Grapefruit'],
            Lemons: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/lemons.jpg?itok=W6bdcxfq', 'Lemons'],
            Oranges: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/oranges.jpg?itok=iw6d6Ial', 'Oranges'],
            Peaches: ['url', 'seasonal details'],
            Pears: ['url', 'seasonal details'],
            Peas: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/peas.jpg?itok=T6KM1bft', 'Peas'],
            Pomegranates: ['url', 'seasonal details'],
            Potatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/potatoes.jpg?itok=e3KKT2ta', 'Potatoes'],
            Pumpkins: ['url', 'seasonal details'],
            Rasberries: ['url', 'seasonal details'],
            Spinach: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/spinach.jpg?itok=vs_2VYRs', 'Spinach'],
            Squash: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/summer%20squash.jpg?itok=QPc9_LQw', 'Squash'],
            SweetCorn: ['url', 'seasonal details'],
            Tomatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/tomatoes.jpg?itok=JhlM9Onh', 'Tomatoes']},
        AR: {
            Apples: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/apples_2.jpg?h=65b39431&itok=MoJheg5x', 'Apples'],
            AsianPears: ['url', 'seasonal details'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Cucumbers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cucumbers2.jpg?itok=YISLeW4e', 'Cucumbers'],
            Eggplant: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/eggplant.jpg?itok=FyEpBSrd', 'Eggplant'],
            Greens: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/collards.jpg?itok=io-TE89d', 'Greens'],
            Herbs: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/2021-04/herbs.jpg?itok=g_UukhUg', 'Herbs'],
            Muscadines: ['url', 'seasonal details'],
            Peaches: ['url', 'seasonal details'],
            Peppers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/bell%20peppers.jpg?h=9f30bee3&itok=PKmzyeNv', 'Peppers'],
            Rasberries: ['url', 'seasonal details'],
            Pumpkins: ['url', 'seasonal details'],
            Squash: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/summer%20squash.jpg?itok=QPc9_LQw', 'Squash'],
            SweetCorn: ['url', 'seasonal details'],
            SweetPotatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/potatoes.jpg?itok=e3KKT2ta', 'Sweet Potatoes'],
            Tomatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/tomatoes.jpg?itok=JhlM9Onh', 'Tomatoes'],
            Watermelons: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/watermelon.jpg?itok=6EdNOdUo', 'Watermelons']},
        CA: {
            Arugula: ['https://agriexotic.com/wp-content/uploads/2022/05/arugula.jpg', 'Arugula'],
            Beans: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/green%20beans.jpg?itok=rXeZ3ZNC', 'Beans'],
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            BlackEyedPeas: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/peas.jpg?itok=T6KM1bft', 'Peas'],
            BokChoy: ['https://www.greedygourmet.com/wp-content/uploads/2020/04/boychoy1-683x1024.jpg', 'Bok Choy'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Carrots: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/carrots.jpg?h=c8b8df1c&itok=wy-UEFSx', 'Carrots'],
            Cauliflower: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cauliflower.jpg?h=c8b8df1c&itok=XVi8_6bg', 'Cauliflower'],
            Celery: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/celery.jpg?h=8bf7d235&itok=5W-SSPx2', 'Celery'],
            Chard: ['url', 'seasonal details'],
            Herbs: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/2021-04/herbs.jpg?itok=g_UukhUg', 'Herbs'],
            Cucumbers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cucumbers2.jpg?itok=YISLeW4e', 'Cucumbers'],
            Eggplant: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/eggplant.jpg?itok=FyEpBSrd', 'Eggplant'],
            EnglishPeas: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/peas.jpg?itok=T6KM1bft', 'Peas'],
            Fennel: ['https://pcdn.columbian.com/wp-content/uploads/2019/06/0614_fea_fennel.jpg', 'Fennel'],
            Kale: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/kale.jpg?itok=Zn8Cux6F', 'Kale'],
            Leeks: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/leeks.jpg?itok=Y8Xlwrgp', 'Leeks'],
            Lemons: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/lemons.jpg?itok=W6bdcxfq', 'Lemons'],
            Lettuce: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/lettuce.jpg?itok=MvYHJXC5', 'Lettuce'],
            Okra: ['url', 'seasonal details'],
            Peppers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/bell%20peppers.jpg?h=9f30bee3&itok=PKmzyeNv', 'Peppers'],
            Pumpkins: ['url', 'seasonal details'],
            Radishes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/radish.jpg?itok=hNtVXvda', 'Radishes'],
            Rasberries: ['url', 'seasonal details'],
            SnapPeas: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/peas.jpg?itok=T6KM1bft', 'Peas'],
            Spinach: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/spinach.jpg?itok=vs_2VYRs', 'Spinach'],
            StringBeans: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/green%20beans.jpg?itok=rXeZ3ZNC', 'Beans'],
            Squash: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/summer%20squash.jpg?itok=QPc9_LQw', 'Squash'],
            Tomatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/tomatoes.jpg?itok=JhlM9Onh', 'Tomatoes'],
            Turnips: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/turnips.jpg?itok=ZoofKY5b', 'Turnips']},
        CO: {
            Apples: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/apples_2.jpg?h=65b39431&itok=MoJheg5x', 'Apples'],
            Arugula: ['https://agriexotic.com/wp-content/uploads/2022/05/arugula.jpg', 'Arugula'],
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage']},
        CT: {
            Apples: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/apples_2.jpg?h=65b39431&itok=MoJheg5x', 'Apples'],
            Beans: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/green%20beans.jpg?itok=rXeZ3ZNC', 'Beans'],
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            Blueberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/blueberries.jpg?h=2c763480&itok=GL0AQ5xh', 'Blueberries'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage']},
        DE: {
            Apples: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/apples_2.jpg?h=65b39431&itok=MoJheg5x', 'Apples'],
            BlackEyedPeas: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/peas.jpg?itok=T6KM1bft', 'Peas'],
            BrusselSprouts: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/brusselssprouts.jpg?h=c8b8df1c&itok=WsaCU63W', 'Brussel Sprouts'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Carrots: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/carrots.jpg?h=c8b8df1c&itok=wy-UEFSx', 'Carrots'],
            Cauliflower: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cauliflower.jpg?h=c8b8df1c&itok=XVi8_6bg', 'Cauliflower']},
        FL: {
            Avocado: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/avocado.jpg?h=23e79702&itok=V-RSvLPH', 'Avocado'],
            Cucumber: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cucumbers2.jpg?itok=YISLeW4e', 'Cucumber'],
            Grapefruit: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/grapefruit.jpg?itok=EXi1a_uq', 'Grapefruit'],
            Mushrooms: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/mushrooms.jpg?h=b754914e&itok=Kldbq8Du', 'Mushrooms'],
            Oranges: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/oranges.jpg?itok=iw6d6Ial', 'Oranges']},
    },
    Winter: {
        AL: {
            Greens: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/collards.jpg?itok=io-TE89d', 'Greens'],
            Herbs: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/2021-04/herbs.jpg?itok=g_UukhUg', 'Herbs'],
            Persimmons: ['https://nutritioncenter.ctahr.hawaii.edu/wp-content/uploads/2022/06/persimmons-japanese-raw.jpg', 'Persimmons'],
            SweetPotatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/potatoes.jpg?itok=e3KKT2ta', 'Sweet Potatoes'],
            Rutabaga: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/rutabaga.jpg?itok=ohK71nUz', 'Rutabaga'],
            Squash: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/summer%20squash.jpg?itok=QPc9_LQw', 'Squash']},
        AK: {
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Carrots: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/carrots.jpg?h=c8b8df1c&itok=wy-UEFSx', 'Carrots'],
            Onions: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/onions.jpg?itok=oLl36ia1', 'Onions'],
            Potatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/potatoes.jpg?itok=e3KKT2ta', 'Potatoes'],
            Turnips: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/turnips.jpg?itok=ZoofKY5b', 'Turnips']},
        AZ: {
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Cauliflower: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cauliflower.jpg?h=c8b8df1c&itok=XVi8_6bg', 'Cauliflower'],
            Carrots: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/carrots.jpg?h=c8b8df1c&itok=wy-UEFSx', 'Carrots'],
            Celery: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/celery.jpg?h=8bf7d235&itok=5W-SSPx2', 'Celery'],
            Grapefruit: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/grapefruit.jpg?itok=EXi1a_uq', 'Grapefruit'],
            Lemons: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/lemons.jpg?itok=W6bdcxfq', 'Lemons'],
            Oranges: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/oranges.jpg?itok=iw6d6Ial', 'Oranges'],
            Spinach: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/spinach.jpg?itok=vs_2VYRs', 'Spinach'],
            Strawberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/strawberries.jpg?itok=WXVLbw1Q', 'Strawberries'],
            Tangerines: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/oranges.jpg?itok=iw6d6Ial', 'Tangerines']},
        AR: {
            Spinach: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/spinach.jpg?itok=vs_2VYRs', 'Spinach'],
            Squash: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/summer%20squash.jpg?itok=QPc9_LQw', 'Squash'],
            Turnips: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/turnips.jpg?itok=ZoofKY5b', 'Turnips']},
        CA: {
            Arugula: ['https://agriexotic.com/wp-content/uploads/2022/05/arugula.jpg', 'Arugula'],
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            BokChoy: ['https://www.greedygourmet.com/wp-content/uploads/2020/04/boychoy1-683x1024.jpg', 'Bok Choy'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Carrots: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/carrots.jpg?h=c8b8df1c&itok=wy-UEFSx', 'Carrots'],
            Cauliflower: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cauliflower.jpg?h=c8b8df1c&itok=XVi8_6bg', 'Cauliflower'],
            Celery: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/celery.jpg?h=8bf7d235&itok=5W-SSPx2', 'Celery'],
            Herbs: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/2021-04/herbs.jpg?itok=g_UukhUg', 'Herbs'],
            Cucumbers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cucumbers2.jpg?itok=YISLeW4e', 'Cucumbers'],
            Eggplant: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/eggplant.jpg?itok=FyEpBSrd', 'Eggplant'],
            EnglishPeas: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/peas.jpg?itok=T6KM1bft', 'Peas'],
            Fennel: ['https://pcdn.columbian.com/wp-content/uploads/2019/06/0614_fea_fennel.jpg', 'Fennel'],
            Grapefruit: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/grapefruit.jpg?itok=EXi1a_uq', 'Grapefruit'],
            Kale: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/kale.jpg?itok=Zn8Cux6F', 'Kale'],
            Leeks: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/leeks.jpg?itok=Y8Xlwrgp', 'Leeks'],
            Lemons: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/lemons.jpg?itok=W6bdcxfq', 'Lemons'],
            Lettuce: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/lettuce.jpg?itok=MvYHJXC5', 'Lettuce'],
            Mandarins: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/oranges.jpg?itok=iw6d6Ial', 'Mandarins'],
            Oranges: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/oranges.jpg?itok=iw6d6Ial', 'Oranges'],
            Peppers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/bell%20peppers.jpg?h=9f30bee3&itok=PKmzyeNv', 'Peppers'],
            Radishes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/radish.jpg?itok=hNtVXvda', 'Radishes'],
            SnapPeas: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/peas.jpg?itok=T6KM1bft', 'Peas'],
            Spinach: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/spinach.jpg?itok=vs_2VYRs', 'Spinach'],
            Strawberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/strawberries.jpg?itok=WXVLbw1Q', 'Strawberries'],
            Turnips: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/turnips.jpg?itok=ZoofKY5b', 'Turnips']},

        CO: {
            Cucumbers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cucumbers2.jpg?itok=YISLeW4e', 'Cucumbers'],
            Potatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/potatoes.jpg?itok=e3KKT2ta', 'Potatoes'],
            Tomatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/tomatoes.jpg?itok=JhlM9Onh', 'Tomatoes'],
            Squash: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/summer%20squash.jpg?itok=QPc9_LQw', 'Squash']},
        CT: {
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            Cauliflower: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cauliflower.jpg?h=c8b8df1c&itok=XVi8_6bg', 'Cauliflower'],
            Potatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/potatoes.jpg?itok=e3KKT2ta', 'Potatoes'],
            Turnips: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/turnips.jpg?itok=ZoofKY5b', 'Turnips']},
        DE: {
            Turnips: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/turnips.jpg?itok=ZoofKY5b', 'Turnips']},
        FL: {
            BellPeppers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/bell%20peppers.jpg?h=9f30bee3&itok=PKmzyeNv', 'Peppers'],
            Cauliflower: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cauliflower.jpg?h=c8b8df1c&itok=XVi8_6bg', 'Cauliflower'],
            Celery: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/celery.jpg?h=8bf7d235&itok=5W-SSPx2', 'Celery'],
            Eggplant: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/eggplant.jpg?itok=FyEpBSrd', 'Eggplant'],
            Grapefruit: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/grapefruit.jpg?itok=EXi1a_uq', 'Grapefruit']},
    },
    Spring: {
        AL: {
            Beans: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/green%20beans.jpg?itok=rXeZ3ZNC', 'Beans'],
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            Blueberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/blueberries.jpg?h=2c763480&itok=GL0AQ5xh', 'Blueberries'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Cauliflower: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cauliflower.jpg?h=c8b8df1c&itok=XVi8_6bg', 'Cauliflower'],
            Corn: ['url', 'seasonal details'],
            Cucumbers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cucumbers2.jpg?itok=YISLeW4e', 'Cucumbers'],
            Eggplant: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/eggplant.jpg?itok=FyEpBSrd', 'Eggplant'],
            Greens: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/collards.jpg?itok=io-TE89d', 'Greens'],
            Herbs: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/2021-04/herbs.jpg?itok=g_UukhUg', 'Herbs'],
            Lettuce: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/lettuce.jpg?itok=MvYHJXC5', 'Lettuce'],
            Onions: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/onions.jpg?itok=oLl36ia1', 'Onions'],
            Peaches: ['url', 'seasonal details'],
            Peas: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/peas.jpg?itok=T6KM1bft', 'Peas'],
            SweetPotatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/potatoes.jpg?itok=e3KKT2ta', 'Sweet Potatoes'],
            Spinach: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/spinach.jpg?itok=vs_2VYRs', 'Spinach'],
            Squash: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/summer%20squash.jpg?itok=QPc9_LQw', 'Squash'],
            Strawberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/strawberries.jpg?itok=WXVLbw1Q', 'Strawberries']},
        AK: {
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            Carrots: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/carrots.jpg?h=c8b8df1c&itok=wy-UEFSx', 'Carrots'],
            Potatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/potatoes.jpg?itok=e3KKT2ta', 'Potatoes'],
            Rhubarb: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/rhubarb.jpg?itok=N3ThN-Kr', 'Rhubarb'],
            Tomatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/tomatoes.jpg?itok=JhlM9Onh', 'Tomatoes']},
        AZ: {
            Apricots: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/apricots.jpg?h=c8b8df1c&itok=PiYJ9sg1', 'Apricots'],
            Asparagus: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/asparagus.jpg?h=f2c22e70&itok=sa1Ja1N0', 'Asparagus'],
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Cauliflower: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cauliflower.jpg?h=c8b8df1c&itok=XVi8_6bg', 'Cauliflower'],
            Carrots: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/carrots.jpg?h=c8b8df1c&itok=wy-UEFSx', 'Carrots'],
            Celery: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/celery.jpg?h=8bf7d235&itok=5W-SSPx2', 'Celery'],
            Cucumbers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cucumbers2.jpg?itok=YISLeW4e', 'Cucumbers'],
            Dates: ['url', 'seasonal details'],
            Eggplants: ['url', 'seasonal details'],
            Grapefruit: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/grapefruit.jpg?itok=EXi1a_uq', 'Grapefruit'],
            Lemons: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/lemons.jpg?itok=W6bdcxfq', 'Lemons'],
            Onions: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/onions.jpg?itok=oLl36ia1', 'Onions'],
            Oranges: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/oranges.jpg?itok=iw6d6Ial', 'Oranges'],
            Spinach: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/spinach.jpg?itok=vs_2VYRs', 'Spinach'],
            Squash: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/summer%20squash.jpg?itok=QPc9_LQw', 'Squash'],
            Strawberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/strawberries.jpg?itok=WXVLbw1Q', 'Strawberries'],
            Tangerines: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/oranges.jpg?itok=iw6d6Ial', 'Tangerines'],
            Tomatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/tomatoes.jpg?itok=JhlM9Onh', 'Tomatoes']},
        AR: {
            Asparagus: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/asparagus.jpg?h=f2c22e70&itok=sa1Ja1N0', 'Asparagus'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Cucumbers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cucumbers2.jpg?itok=YISLeW4e', 'Cucumbers'],
            Greens: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/collards.jpg?itok=io-TE89d', 'Greens'],
            Herbs: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/2021-04/herbs.jpg?itok=g_UukhUg', 'Herbs'],
            Peas: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/peas.jpg?itok=T6KM1bft', 'Peas'],
            Potatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/potatoes.jpg?itok=e3KKT2ta', 'Potatoes'],
            Rhubarb: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/rhubarb.jpg?itok=N3ThN-Kr', 'Rhubarb'],
            Strawberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/strawberries.jpg?itok=WXVLbw1Q', 'Strawberries']},
        CA: {
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            BokChoy: ['https://www.greedygourmet.com/wp-content/uploads/2020/04/boychoy1-683x1024.jpg', 'Bok Choy'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Carrots: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/carrots.jpg?h=c8b8df1c&itok=wy-UEFSx', 'Carrots'],
            Cauliflower: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cauliflower.jpg?h=c8b8df1c&itok=XVi8_6bg', 'Cauliflower']},
        CO: {
            Cucumbers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cucumbers2.jpg?itok=YISLeW4e', 'Cucumbers'],
            Lettuce: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/lettuce.jpg?itok=MvYHJXC5', 'Lettuce'],
            Potatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/potatoes.jpg?itok=e3KKT2ta', 'Potatoes'],
            Spinach: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/spinach.jpg?itok=vs_2VYRs', 'Spinach'],
            Tomatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/tomatoes.jpg?itok=JhlM9Onh', 'Tomatoes']},
        CT: {
            Asparagus: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/asparagus.jpg?h=f2c22e70&itok=sa1Ja1N0', 'Asparagus'],
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            Collards: ['url', 'seasonal details'],
            Peas: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/peas.jpg?itok=T6KM1bft', 'Peas'],
            Rhubarb: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/rhubarb.jpg?itok=N3ThN-Kr', 'Rhubarb'],
            Spinach: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/spinach.jpg?itok=vs_2VYRs', 'Spinach']},
        DE: {
            Asparagus: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/asparagus.jpg?h=f2c22e70&itok=sa1Ja1N0', 'Asparagus'],
            GreenOnions: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/onions.jpg?itok=oLl36ia1', 'Onions'],
            Lettuce: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/lettuce.jpg?itok=MvYHJXC5', 'Lettuce'],
            Mushrooms: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/mushrooms.jpg?h=b754914e&itok=Kldbq8Du', 'Mushrooms'],
            Peas: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/peas.jpg?itok=T6KM1bft', 'Peas'],
            Spinach: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/spinach.jpg?itok=vs_2VYRs', 'Spinach'],
            Turnips: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/turnips.jpg?itok=ZoofKY5b', 'Turnips']},
        FL: {
            BellPeppers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/bell%20peppers.jpg?h=9f30bee3&itok=PKmzyeNv', 'Peppers'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Celery: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/celery.jpg?h=8bf7d235&itok=5W-SSPx2', 'Celery'],
            Cucumber: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cucumbers2.jpg?itok=YISLeW4e', 'Cucumber'],
            Eggplant: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/eggplant.jpg?itok=FyEpBSrd', 'Eggplant'],
            Grapefruit: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/grapefruit.jpg?itok=EXi1a_uq', 'Grapefruit']},


    },
    Summer: {
        AL: {
            Apples: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/apples_2.jpg?h=65b39431&itok=MoJheg5x', 'Apples'],
            Beans: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/green%20beans.jpg?itok=rXeZ3ZNC', 'Beans'],
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            Blackberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/blackberries.jpg?h=c8b8df1c&itok=sViCstBs', 'Blackberries'],
            Blueberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/blueberries.jpg?h=2c763480&itok=GL0AQ5xh', 'Blueberries'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Cantaloupes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cantaloupe.jpg?h=c8b8df1c&itok=hLzdNse1', 'Cantelopes'],
            Cauliflower: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cauliflower.jpg?h=c8b8df1c&itok=XVi8_6bg', 'Cauliflower'],
            Corn: ['url', 'seasonal details'],
            Cucumbers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cucumbers2.jpg?itok=YISLeW4e', 'Cucumbers'],
            Eggplant: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasofnal-produce/2018-05/eggplant.jpg?itok=FyEpBSrd', 'Eggplant'],
            Figs: ['https://plantsbymail.com/wp-content/uploads/2018/06/Fig_Little_Miss_Figgy_MAIN.jpg', 'Figs'],
            Grapes: ['url', 'seasonal details'],
            Greens: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/collards.jpg?itok=io-TE89d', 'Greens'],
            Herbs: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/2021-04/herbs.jpg?itok=g_UukhUg', 'Herbs'],
            Lettuce: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/lettuce.jpg?itok=MvYHJXC5', 'Lettuce'],
            Okra: ['url', 'seasonal details'],
            Onions: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/onions.jpg?itok=oLl36ia1', 'Onions'],
            Peaches: ['url', 'seasonal details'],
            Peas: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/peas.jpg?itok=T6KM1bft', 'Peas'],
            Peppers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/bell%20peppers.jpg?h=9f30bee3&itok=PKmzyeNv', 'Peppers'],
            SweetPotatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/potatoes.jpg?itok=e3KKT2ta', 'Sweet Potatoes'],
            Spinach: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/spinach.jpg?itok=vs_2VYRs', 'Spinach'],
            Squash: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/summer%20squash.jpg?itok=QPc9_LQw', 'Squash'],
            Strawberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/strawberries.jpg?itok=WXVLbw1Q', 'Strawberries'],
            Tomatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/tomatoes.jpg?itok=JhlM9Onh', 'Tomatoes'],
            Watermelons: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/watermelon.jpg?itok=6EdNOdUo', 'Watermelons']},
        AK: {
            Beans: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/green%20beans.jpg?itok=rXeZ3ZNC', 'Beans'],
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            BrusselSprouts: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/brusselssprouts.jpg?h=c8b8df1c&itok=WsaCU63W', 'Brussel Sprouts'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Carrots: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/carrots.jpg?h=c8b8df1c&itok=wy-UEFSx', 'Carrots'],
            Cauliflower: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cauliflower.jpg?h=c8b8df1c&itok=XVi8_6bg', 'Cauliflower'],
            Celery: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/celery.jpg?h=8bf7d235&itok=5W-SSPx2', 'Celery'],
            Chard: ['url', 'seasonal details'],
            CollardGreens: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/collards.jpg?itok=io-TE89d', 'Greens'],
            Cucumbers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cucumbers2.jpg?itok=YISLeW4e', 'Cucumbers'],
            Kale: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/kale.jpg?itok=Zn8Cux6F', 'Kale'],
            Lettuce: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/lettuce.jpg?itok=MvYHJXC5', 'Lettuce'],
            Onions: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/onions.jpg?itok=oLl36ia1', 'Onions'],
            Peas: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/peas.jpg?itok=T6KM1bft', 'Peas'],
            Potatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/potatoes.jpg?itok=e3KKT2ta', 'Potatoes'],
            Radishes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/radish.jpg?itok=hNtVXvda', 'Radishes'],
            Rasberries: ['url', 'seasonal details'],
            Rhubarb: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/rhubarb.jpg?itok=N3ThN-Kr', 'Rhubarb'],
            Spinach: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/spinach.jpg?itok=vs_2VYRs', 'Spinach'],
            Strawberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/strawberries.jpg?itok=WXVLbw1Q', 'Strawberries'],
            Tomatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/tomatoes.jpg?itok=JhlM9Onh', 'Tomatoes'],
            Turnips: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/turnips.jpg?itok=ZoofKY5b', 'Turnips'],
            Squash: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/summer%20squash.jpg?itok=QPc9_LQw', 'Squash'],
            Zucchini: ['url', 'seasonal details']},
        AZ: {
            Apples: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/apples_2.jpg?h=65b39431&itok=MoJheg5x', 'Apples'],
            Apricots: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/apricots.jpg?h=c8b8df1c&itok=PiYJ9sg1', 'seasonal details'],
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            Blackberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/blackberries.jpg?h=c8b8df1c&itok=sViCstBs', 'Blackberries'],
            Blueberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/blueberries.jpg?h=2c763480&itok=GL0AQ5xh', 'Blueberries'],
            Cucumbers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cucumbers2.jpg?itok=YISLeW4e', 'Cucumbers'],
            Dates: ['url', 'seasonal details'],
            Eggplants: ['url', 'seasonal details'],
            Figs: ['https://plantsbymail.com/wp-conFigstent/uploads/2018/06/Fig_Little_Miss_Figgy_MAIN.jpg', 'Figs'],
            Grapes: ['url', 'seasonal details'],
            Melons: ['url', 'seasonal details'],
            Nectarines: ['url', 'seasonal details'],
            Onions: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/onions.jpg?itok=oLl36ia1', 'Onions'],
            Peaches: ['url', 'seasonal details'],
            Peppers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/bell%20peppers.jpg?h=9f30bee3&itok=PKmzyeNv', 'Peppers'],
            Plums: ['url', 'seasonal details'],
            Pomegranates: ['url', 'seasonal details'],
            Rasberries: ['url', 'seasonal details'],
            Squash: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/summer%20squash.jpg?itok=QPc9_LQw', 'Squash'],
            SweetCorn: ['url', 'seasonal details'],
            Tomatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/tomatoes.jpg?itok=JhlM9Onh', 'Tomatoes']},
        AR: {
            Apples: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/apples_2.jpg?h=65b39431&itok=MoJheg5x', 'Apples'],
            AsianPears: ['url', 'seasonal details'],
            Asparagus: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/asparagus.jpg?h=f2c22e70&itok=sa1Ja1N0', 'Asparagus'],
            Beans: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/green%20beans.jpg?itok=rXeZ3ZNC', 'Beans'],
            Blackberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/blackberries.jpg?h=c8b8df1c&itok=sViCstBs', 'Blackberries'],
            Blueberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/blueberries.jpg?h=2c763480&itok=GL0AQ5xh', 'Blueberries'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Cantaloupes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cantaloupe.jpg?h=c8b8df1c&itok=hLzdNse1', 'Cantelopes'],
            Cherries: ['url', 'seasonal details'],
            Cucumbers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cucumbers2.jpg?itok=YISLeW4e', 'Cucumbers'],
            Eggplant: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/eggplant.jpg?itok=FyEpBSrd', 'Eggplant'],
            Grapes: ['url', 'seasonal details'],
            Greens: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/collards.jpg?itok=io-TE89d', 'Greens'],
            Herbs: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/2021-04/herbs.jpg?itok=g_UukhUg', 'Herbs'],
            Nectarines: ['url', 'seasonal details'],
            Peaches: ['url', 'seasonal details'],
            Peppers: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/bell%20peppers.jpg?h=9f30bee3&itok=PKmzyeNv', 'Peppers'],
            Plums: ['url', 'seasonal details'],
            Potatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/potatoes.jpg?itok=e3KKT2ta', 'Potatoes'],
            Rasberries: ['url', 'seasonal details'],
            Rhubarb: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/rhubarb.jpg?itok=N3ThN-Kr', 'Rhubarb'],
            Squash: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/summer%20squash.jpg?itok=QPc9_LQw', 'Squash'],
            Strawberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/strawberries.jpg?itok=WXVLbw1Q', 'Strawberries'],
            SweetCorn: ['url', 'seasonal details'],
            Tomatoes: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/tomatoes.jpg?itok=JhlM9Onh', 'Tomatoes'],
            Watermelons: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/watermelon.jpg?itok=6EdNOdUo', 'Watermelons']},
        CA: {
            Apricots: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/apricots.jpg?h=c8b8df1c&itok=PiYJ9sg1', 'Apricots'],
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZjBeets', 'Beets'],
            BlackEyedPeas: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/peas.jpg?itok=T6KM1bft', 'Peas'],
            BokChoy: ['https://www.greedygourmet.com/wp-content/uploads/2020/04/boychoy1-683x1024.jpg', 'Bok Choy']},
        CO: {
            Apricots: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/apricots.jpg?h=c8b8df1c&itok=PiYJ9sg1', 'Apricots'],
            Arugula: ['https://agriexotic.com/wp-content/uploads/2022/05/arugula.jpg', 'Arugula'],
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Cauliflower: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cauliflower.jpg?h=c8b8df1c&itok=XVi8_6bg', 'Cauliflower']},
        CT: {
            Apples: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/apples_2.jpg?h=65b39431&itok=MoJheg5x', 'Apples'],
            Beans: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/green%20beans.jpg?itok=rXeZ3ZNC', 'Beans'],
            Beets: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/beets.jpg?h=c8b8df1c&itok=tJDWRZje', 'Beets'],
            Blackberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/blackberries.jpg?h=c8b8df1c&itok=sViCstBs', 'Blackberries'],
            Blueberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/blueberries.jpg?h=2c763480&itok=GL0AQ5xh', 'Blueberries'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage']},
        DE: {
            Apples: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/apples_2.jpg?h=65b39431&itok=MoJheg5x', 'Apples'],
            Blueberries: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/blueberries.jpg?h=2c763480&itok=GL0AQ5xh', 'Blueberries'],
            Broccoli: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/broccoli.jpg?h=65b39431&itok=xglOu8vA', 'Broccoli'],
            Cabbage: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cabbage.jpg?h=ea25e381&itok=c6jva3pn', 'Cabbage'],
            Canteloupe: ['url', 'seasonal details'],
            Carrots: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/carrots.jpg?h=c8b8df1c&itok=wy-UEFSx', 'Carrots'],
            Cauliflower: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/cauliflower.jpg?h=c8b8df1c&itok=XVi8_6bg', 'Cauliflower']},
        FL: {
            Avocado: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/avocado.jpg?h=23e79702&itok=V-RSvLPH', 'Avocado'],
            Guava: ['url', 'seasonal details'],
            Mango: ['url', 'seasonal details'],
            Mushrooms: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/mushrooms.jpg?h=b754914e&itok=Kldbq8Du', 'Mushrooms'],
            Watermelons: ['https://snaped.fns.usda.gov/sites/default/files/styles/crop_ratio_7_5/public/seasonal-produce/2018-05/watermelon.jpg?itok=6EdNOdUo', 'Watermelons']},
    }
};

export default seasonalItems;
