
const seasonalItems = {
    Fall: {
        AL: {
            Apples: 'seasonal details',
            Beans: 'seasonal details',
            Blackberries: 'seasonal details',
            Cabbage: 'seasonal details',
            Cantaloupes: 'seasonal details',
            Citrus: 'seasonal details',
            Corn: 'seasonal details',
            Cucumbers: 'seasonal details',
            Eggplant: 'seasonal details',
            Figs: 'seasonal details',
            Grapes: 'seasonal details',
            Greens: 'seasonal details',
            Herbs: 'seasonal details',
            Lettuce: 'seasonal details',
            Okra: 'seasonal details',
            Peaches: 'seasonal details',
            Peas: 'seasonal details',
            Pecans: 'seasonal details',
            Persimmons: 'seasonal details',
            Peppers: 'seasonal details',
            SweetPotatoes: 'seasonal details',
            Pumpkins: 'seasonal details',
            Rutabaga: 'seasonal details',
            Squash: 'seasonal details',
            Tomatoes: 'seasonal details',
            Watermelons: 'seasonal details'},

        AK: {
            Beans: 'seasonal details',
            Beets: 'seasonal details',
            Broccoli: 'seasonal details',
            BrusselSprouts: 'seasonal details',
            Cabbage: 'seasonal details',
            Carrots: 'seasonal details',
            Cauliflower: 'seasonal details',
            Celery: 'seasonal details',
            Chard: 'seasonal details',
            CollardGreens: 'seasonal details',
            Cucumbers: 'seasonal details',
            Kale: 'seasonal details',
            Leeks: 'seasonal details',
            Lettuce: 'seasonal details',
            Onions: 'seasonal details',
            Potatoes: 'seasonal details',
            Pumpkins: 'seasonal details',
            Radishes: 'seasonal details',
            Rhubarb: 'seasonal details',
            Spinach: 'seasonal details',
            Strawberries: 'seasonal details',
            Tomatoes: 'seasonal details',
            Turnips: 'seasonal details',
            Squash: 'seasonal details'},
        AZ: {
            Apples: 'seasonal details',
            Beets: 'seasonal details',
            Broccoli: 'seasonal details',
            Cucumbers: 'seasonal details',
            Dates: 'seasonal details',
            Eggplants: 'seasonal details',
            Grapefruit: 'seasonal details',
            Lemons: 'seasonal details',
            Oranges: 'seasonal details',
            Peaches: 'seasonal details',
            Pears: 'seasonal details',
            Peas: 'seasonal details',
            Pomegranates: 'seasonal details',
            Potatoes: 'seasonal details',
            Pumpkins: 'seasonal details',
            Rasberries: 'seasonal details',
            Spinach: 'seasonal details',
            Squash: 'seasonal details',
            SweetCorn: 'seasonal details',
            Tomatoes: 'seasonal details'}
    },
    Winter: {
        AL: {
            Citrus: 'seasonal details',
            Greens: 'seasonal details',
            Herbs: 'seasonal details',
            Pecans: 'seasonal details',
            Persimmons: 'seasonal details',
            SweetPotatoes: 'seasonal details',
            Rutabaga: 'seasonal details',
            Squash: 'seasonal details'},
        AK: {
            Beets: 'seasonal details',
            Cabbage: 'seasonal details',
            Carrots: 'seasonal details',
            Onions: 'seasonal details',
            Potatoes: 'seasonal details',
            Turnips: 'seasonal details'},
        AZ: {
            Beets: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details',
            Cauliflower: 'seasonal details',
            Carrots: 'seasonal details',
            Celery: 'seasonal details',
            Grapefruit: 'seasonal details',
            Lemons: 'seasonal details',
            Oranges: 'seasonal details',
            Spinach: 'seasonal details',
            Strawberries: 'seasonal details',
            Tangerines: 'seasonal details'},
    },
    Spring: {
        AL: {
            Beans: 'seasonal details',
            Beets: 'seasonal details',
            Blueberries: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details',
            Cauliflower: 'seasonal details',
            Corn: 'seasonal details',
            Cucumbers: 'seasonal details',
            Eggplant: 'seasonal details',
            Greens: 'seasonal details',
            Herbs: 'seasonal details',
            Lettuce: 'seasonal details',
            Onions: 'seasonal details',
            Peaches: 'seasonal details',
            Peas: 'seasonal details',
            Pecans: 'seasonal details',
            SweetPotatoes: 'seasonal details',
            Spinach: 'seasonal details',
            Squash: 'seasonal details',
            Strawberries: 'seasonal details'},
        AK: {
            Beets: 'seasonal details',
            Carrots: 'seasonal details',
            Pottatoes: 'seasonal details',
            Rhubsrb: 'seasonal details',
            Tomatoes: 'seasonal details'},
        AZ: {
            Apricots: 'seasonal details',
            Asparagus: 'seasonal details',
            Beets: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details',
            Cauliflower: 'seasonal details',
            Carrots: 'seasonal details',
            Celery: 'seasonal details',
            Cucumbers: 'seasonal details',
            Dates: 'seasonal details',
            Eggplants: 'seasonal details',
            Grapefruit: 'seasonal details',
            Lemons: 'seasonal details',
            Onions: 'seasonal details',
            Oranges: 'seasonal details',
            Spinach: 'seasonal details',
            Squash: 'seasonal details',
            Strawberries: 'seasonal details',
            Tangerines: 'seasonal details',
            Tomatoes: 'seasonal details'},

    },
    Summer: {
        AL: {
            Apples: 'seasonal details',
            Beans: 'seasonal details',
            Beets: 'seasonal details',
            Blackberries: 'seasonal details',
            Blueberries: 'seasonal details',
            Broccoli: 'seasonal details',
            Cabbage: 'seasonal details',
            Cantaloupes: 'seasonal details',
            Cauliflower: 'seasonal details',
            Corn: 'seasonal details',
            Cucumbers: 'seasonal details',
            Eggplant: 'seasonal details',
            Figs: 'seasonal details',
            Grapes: 'seasonal details',
            Greens: 'seasonal details',
            Herbs: 'seasonal details',
            Lettuce: 'seasonal details',
            Okra: 'seasonal details',
            Onions: 'seasonal details',
            Peaches: 'seasonal details',
            Peas: 'seasonal details',
            Pecans: 'seasonal details',
            Peppers: 'seasonal details',
            SweetPotatoes: 'seasonal details',
            Spinach: 'seasonal details',
            Squash: 'seasonal details',
            Strawberries: 'seasonal details',
            Tomatoes: 'seasonal details',
            Watermelons: 'seasonal details'},
        AK: {
            Beans: 'seasonal details',
            Beets: 'seasonal details',
            Broccoli: 'seasonal details',
            BrusselSprouts: 'seasonal details',
            Cabbage: 'seasonal details',
            Carrots: 'seasonal details',
            Cauliflower: 'seasonal details',
            Celery: 'seasonal details',
            Chard: 'seasonal details',
            CollardGreens: 'seasonal details',
            Cucumbers: 'seasonal details',
            Kale: 'seasonal details',
            Lettuce: 'seasonal details',
            Onions: 'seasonal details',
            Peas: 'seasonal details',
            Potatoes: 'seasonal details',
            Radishes: 'seasonal details',
            Rasberries: 'seasonal details',
            Rhubarb: 'seasonal details',
            Spinach: 'seasonal details',
            Strawberries: 'seasonal details',
            Tomatoes: 'seasonal details',
            Turnips: 'seasonal details',
            Squash: 'seasonal details',
            Zucchini: 'seasonal details'},
        AZ: {
            Apples: 'seasonal details',
            Apricots: 'seasonal details',
            Beets: 'seasonal details',
            Blackberries: 'seasonal details',
            Blueberries: 'seasonal details',
            Cucumbers: 'seasonal details',
            Dates: 'seasonal details',
            Eggplants: 'seasonal details',
            Figs: 'seasonal details',
            Grapes: 'seasonal details',
            Melons: 'seasonal details',
            Nectarines: 'seasonal details',
            Onions: 'seasonal details',
            Peaches: 'seasonal details',
            Peppers: 'seasonal details',
            Plums: 'seasonal details',
            Pomegranates: 'seasonal details',
            Rasberries: 'seasonal details',
            Squash: 'seasonal details',
            SweetCorn: 'seasonal details',
            Tomatoes: 'seasonal details'},
    }
};

export default seasonalItems;
